server {
    listen 80;
    listen [::]:80;
    server_name _;

    location = /nginx-health {
        access_log off;
        include /etc/nginx/conf.d/security-headers.inc;
        default_type text/plain;
        return 200 "ok\n";
    }

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }

    include /etc/nginx/conf.d/locations.inc;
}
